services:
  api1:
    build: ./api1
    container_name: api_1
    ports:
      - "5000:5000"
    depends_on:
      - api2

  api2:
    build: ./api2
    container_name: api_2
    ports:
      - "5001:5001"